### ISSUE TITLE
whats your python ver?

### ISSUE THREAD

**Issue by mngo999** [EnthusiasticXcoder/Maps-View#1]
how do i add tiles to the tiles db

**Comment by EnthusiasticXcoder** [comment]
> how do i add tiles to the tiles db
@mngo999 
you can refer to official documentation of [**TkinterMapView**](https://github.com/TomSchimansky/TkinterMapView). 
also some examples for [load offilne maps](https://github.com/TomSchimansky/TkinterMapView/blob/main/examples/load_offline_tiles.py), [offline tiles](https://github.com/TomSchimansky/TkinterMapView/blob/main/examples/map_with_offline_tiles.py)
